expr: Train BaseNet

device: &device cuda:2

parallel: False

train_data:
  name: Nuro
  root: data/open-nuro-dataset/dataset
  mode: train
  pathology_graph: False

val_data:
  name: Nuro
  root: data/open-nuro-dataset/dataset
  mode: val
  pathology_grapth: False

model:
  name: BaseNet
  enc_channels: 19
  enc_window_size: 3
  enc_seq_len: 51
  enc_node_dim: 256
  mlp_in_features: 256
  mlp_hidden_features: 512
  mlp_class_num: 3

hyperparameters:
  batch_size: 16
  loss_fn: cross-entropy
  optim: AdamW
  lr: 0.0001
  epochs: 100

task: freq

save_name: BaseNet
save_dir: saved