expr: Train ConvNet

device: &device cuda:2

parallel: False

train_data:
  name: Nuro
  root: data/open-nuro-dataset/dataset
  mode: train

val_data:
  name: Nuro
  root: data/open-nuro-dataset/dataset
  mode: val

model:
  name: ConvNet
  channels: 19
  window_size: 5
  seq_len: 51
  node_dim: 128
  mlp_mode: conv_cls
  mlp_hidden_features: 64
  class_num: 3

hyperparameters:
  batch_size: 16
  loss_fn: cross-entropy
  optim: AdamW
  lr: 0.0001
  epochs: 100

task: freq

save_name: ConvNet
save_dir: saved