expr: Train GraphNet

device: &device cuda:2

parallel: False

train_data:
  name: Nuro
  root: data/open-nuro-dataset/dataset
  mode: train

val_data:
  name: Nuro
  root: data/open-nuro-dataset/dataset
  mode: val

model:
  name: GraphNet
  convnet_channels: 19
  convnet_window_size: 5
  convnet_seq_len: 51
  convnet_node_dim: 128
  in_channels: 128 
  hidden_channels: 256
  out_channels: 128
  n_layer: 4
  mlp_hidden_features: 64
  mlp_class_num: 3

hyperparameters:
  batch_size: 16
  loss_fn: cross-entropy
  optim: AdamW
  lr: 0.0001
  epochs: 100

task: graph

save_name: GraphNet
save_dir: saved