expr: Train Transformer Classifier

device: &device cuda:2

parallel: False

train_data:
  name: Nuro
  root: data/open-nuro-dataset/dataset
  mode: train

val_data:
  name: Nuro
  root: data/open-nuro-dataset/dataset
  mode: val

model:
  name: TransformerClassifier
  in_features: 19
  d_model: 128
  n_layer: 6
  attn_heads: 2
  out_dim: 128
  mid_features: 50
  class_num: 3
  device: *device

hyperparameters:
  batch_size: 16
  loss_fn: cross-entropy
  optim: AdamW
  lr: 0.0001
  epochs: 100